#! /bin/bash

read -p "Enter age :" age
if [[ $age -gt 18  &&  $age -lt 30 ]]
#if [ $age -gt 18  -a  $age -lt 30 ]
#if [ $age -gt 18 ] && [ $age -lt 30 ]
then
	echo "Valid age"
else
	echo "invalid age"
fi

